# Exported from Render on 2025-03-01T18:20:57Z
services:
- type: web
  name: bigcommer2ebay
  runtime: docker
  repo: https://github.com/calashockJS/bigcommer2ebay
  plan: free
  envVars:
  - key: LOG_LEVEL
    sync: false
  - key: LOG_DEPRECATIONS_CHANNEL
    sync: false
  - key: LOG_CHANNEL
    value: stack
  - key: BC_WEBHOOK_SECURITY_KEY
    value: dasc23c3-ca45v8v9-90asds
  - key: EBAY_SANDBOX_REDIRECT_URI
    sync: false #value: https://bigcommer2ebay.onrender.com/api/ebay/callback
  - key: EBAY_SANDBOX_CLIENT_SECRET
    sync: false
  - key: EBAY_SANDBOX_CLIENT_ID
    value: LuigiMoc-EcodatIm-SBX-4fce02210-06f07af6
  - key: EBAY_REDIRECT_URI
    sync: false
  - key: EBAY_ENV_TYPE
    value: .sandbox.
  - key: EBAY_CLIENT_SECREATE
    value: SBX-66ebbc6cebcd-6d64-488c-9289-6ad5
  - key: EBAY_CLIENT_ID
    value: LuigiMoc-EcodatIm-SBX-4fce02210-06f07af6
  - key: EBAY_SCOPE
    value: https://api.ebay.com/oauth/api_scope/sell.inventory
  - key: EBAY_SCOPE_SANDBOX
    value: https://api.ebay.com/oauth/api_scope/sell.inventory
  - key: VITE_PUSHER_APP_CLUSTER
    sync: false
  - key: VITE_PUSHER_SCHEME
    sync: false
  - key: VITE_PUSHER_PORT
    sync: false
  - key: VITE_PUSHER_HOST
    sync: false
  - key: VITE_PUSHER_APP_KEY
    sync: false
  - key: VITE_APP_NAME
    sync: false
  - key: PUSHER_APP_CLUSTER
    sync: false
  - key: PUSHER_SCHEME
    sync: false
  - key: PUSHER_PORT
    sync: false
  - key: AWS_USE_PATH_STYLE_ENDPOINT
    sync: false
  - key: AWS_DEFAULT_REGION
    sync: false
  - key: MAIL_FROM_NAME
    sync: false
  - key: MAIL_FROM_ADDRESS
    sync: false
  - key: MAIL_ENCRYPTION
    sync: false
  - key: MAIL_PASSWORD
    sync: false
  - key: MAIL_USERNAME
    sync: false
  - key: MAIL_PORT
    sync: false
  - key: MAIL_HOST
    sync: false
  - key: MAIL_MAILER
    sync: false
  - key: MEMCACHED_HOST
    sync: false
  - key: FILESYSTEM_DISK
    value: local
  - key: BROADCAST_DRIVER
    value: log
  - key: BASE_URL
    sync: false
  - key: APP_URL
    sync: false
  - key: APP_DEBUG
    value: true
  - key: APP_KEY
    sync: false
  - key: APP_ENV
    value: local
  - key: APP_NAME
    value: BigCommerce-to-eBay-Laravel-App
  - key: CACHE_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: database
  - key: SESSION_DRIVER
    value: database
  - key: SESSION_LIFETIME
    value: 120
  - key: EBAY_USERNAME
    value: testuser_judhisahoo
  - key: EBAY_PASSWORD
    value: Jswecom*312#
  - key: DB_CONNECTION
    value: pgsql
  - key: DATABASE_URL
    fromDatabase:
      name: postgres-db
      property: connectionString
  #- key: DB_HOST
  #  value: dpg-cv0br2qj1k6c738fhaeg-a
  #- key: DB_PORT
  #  value: 5432
  #- key: DB_DATABASE

  #- key: DB_USERNAME
  #  fromDatabase:
  #    name: postgres-db
  #    envVarKey: POSTGRES_USER
  #- key: DB_PASSWORD
  #  fromDatabase:
  #    name: postgres-db
  #    envVarKey: POSTGRES_PASSWORD
  disk:
    name: storage
    mountPath: /var/www/html/storage
    sizeGB: 1
  startCommand: |
    php artisan config:clear
    php artisan cache:clear
    php artisan config:cache
    php artisan route:cache
    php artisan migrate --force
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
databases:
- name: postgres-db
  postgresMajorVersion: "16" 
  plan: free
  databaseName: bc2ebay
  user: bc2ebay
version: "1"
